### ISSUE TITLE
Any plans to support JDK 8?

### ISSUE THREAD

**Issue by forma-exacta** [mongounit/mongounit#8]
I get the following error when trying to compile this with JDK 8:

`class file has wrong version 55.0, should be 52.0`

Some quick research seems to indicate that this means mongounit was compiled with JDK 11

**Comment by ychaikin** [comment]
Sorry, but no plans to do that for a couple of reasons:

* When writing the code, I did not stay away from using Java 11 only methods.
* End of life for Java 8 was almost a [year ago](https://www.infoworld.com/article/3269332/oracle-sets-date-for-end-of-java-8-updates.html), so supporting it doesn't make much sense anymore.

However, I will leave this issue open. This project is still completely unknown. If *a lot* of people really really want support for Java 8 and vote up this issue, we can consider it.

However, it's probably better for people to start moving off Java 8. I understand that everyone has that luxury because a customer insists on stay as is. Maybe this will be yet another push to move on? 😉

**Comment by forma-exacta** [comment]
@ychaikin Understood - thanks for the reply. 

> Maybe this will be yet another push to move on?

Eh, I've gotta pick my battles, and this one is low on the list. Hopefully that will be different in a few months.

Anyway, looks like you've got something good here! Good luck with the project.

**Comment by ychaikin** [comment]
@forma-exacta So, I thought about it some more and decided that it's not worth it holding back people who still use Java 8 from using this framework just because of a number of lines in the framework that use Java 9-11 features...

So, look for Java 8 support in the upcoming 1.1.0 version. I might even be able to release it today along with some other updates.

**Comment by ychaikin** [comment]
Done.

**Comment by ychaikin** [comment]
@forma-exacta Just released 1.1.0 with Java 8 support. Please star this repo and let me know how it goes if you end up using this framework.
